### ISSUE TITLE
Random string in search

### ISSUE THREAD

**Issue by svenoaks** [QuickLyric/QuickLyric#196]
It seems to put in random string in the search box sometimes when I start the app, it may be the clipboard contents - is it supposed to that?

**Comment by geecko86** [comment]
I don't remember implementing something like that, no. First time I hear of something like that, too.

The only time it fills in the search bar for you is if you get a NO_RESULT flag. Show me a screenshot next time you have this.

**Comment by svenoaks** [comment]
I installed the app from the Play Store and this is the first thing I saw.

![screenshot apr 4 2017 5-28-18 pm](https://cloud.githubusercontent.com/assets/5206058/24679833/8ba829b2-195c-11e7-88f2-351f4a32abf1.png)

**Comment by svenoaks** [comment]
I have no idea where the string came from, i didn't copy it to clipboard and don't remember seeing that string anywhere.

**Comment by geecko86** [comment]
After taking a quick look:

These are the two places where the searchbar gets assigned a value without immediately doing a search:

* https://github.com/geecko86/QuickLyric/blob/acf5adf32422a822704ed1eead08a679b1edda7e/QuickLyric/src/main/java/com/geecko/QuickLyric/fragment/LyricsViewFragment.java#L951
* https://github.com/geecko86/QuickLyric/blob/3e0487a6e1f72870d65efc6e863777b678340fa0/QuickLyric/src/main/java/com/geecko/QuickLyric/view/MaterialSuggestionsSearchView.java#L119

The second one only happens after you touch the cross to [delete a suggestion](https://github.com/geecko86/QuickLyric/blob/3e0487a6e1f72870d65efc6e863777b678340fa0/QuickLyric/src/main/java/com/geecko/QuickLyric/adapter/SearchSuggestionAdapter.java#L79). 

The first one happens when creating the options menu and the only place it gets a non-null value is [here](https://github.com/geecko86/QuickLyric/blob/acf5adf32422a822704ed1eead08a679b1edda7e/QuickLyric/src/main/java/com/geecko/QuickLyric/fragment/LyricsViewFragment.java#L670), when the lyrics for a track are not found.

Are you sure you haven't played a track with that title?

**Comment by geecko86** [comment]
Sure you didn't listen to this on SoundCloud?

https://soundcloud.com/political-fun-time-happy-hour-deluxe/episode-10-modern-militant-labor-guest-billy-lawson-of-central-florida-afl-cio

**Comment by svenoaks** [comment]
Ah yes that was in there somewhere from Podcast Addict. There is a bug though.

1) Uninstall app.
2) Start long duration podcast in Podcast Addict or probably any other app.
3) Start playing music in Google Play Music
4) Install app from Play Store.

You will see the correct lyrics for the GPM music, but search will be filled in from Podcast Addict.
It shouldn't be filled it because a) not the active media session, b) duration is too long. If I play the long track normally (besides when first installing the app like that) it is correctly not showing it because of the duration. I am thinking bug can only happen when first installing the app.

**Comment by svenoaks** [comment]
It definitely happens through https://github.com/geecko86/QuickLyric/blob/acf5adf32422a822704ed1eead08a679b1edda7e/QuickLyric/src/main/java/com/geecko/QuickLyric/fragment/LyricsViewFragment.java#L670
it calls `fetchLyrics` once with everything null to start the slides and then somehow calls it again with artist and title from an inactive session. Which triggers the `DownloadThread`

**Comment by geecko86** [comment]
Without checking the code, it seems like that call is normal. If the inactive session is for the last song the user played, it's a good thing that the lyrics for it are already there when the onboarding process is dealt with. It makes it clear to the user what the app can do.

@svenoaks The _real_ issue is that that inactive session has the wrong durability. Could you perhaps check if it's specific to Podcast Addict? If so, I can easily reach out to the developer.

**Comment by geecko86** [comment]
I believe this should be fixed. There was some tweaking to do regarding what was happening when changing between players and also QuickLyric now has a blacklist of players which include Chrome and Podcast apps.
