### ISSUE TITLE
RadioDroid

### ISSUE THREAD

**Issue by nicolas-raoul** [QuickLyric/QuickLyric#222]
I often listen to music radios using RadioDroid https://f-droid.org/wiki/page/net.programmierecke.radiodroid2
QuickLyric does not seem to get the hint or recognize the songs, I hit refresh and nothing happens.
I don't know if it is feasible, but that would be great :-)
Cheers!

**Comment by geecko86** [comment]
Hey Nicolas,

QuickLyric needs to obtain information (metadata, position, duration) about a song in order to work. Either through a broadcast pre-KitKat or through the proper APIs after that (RemoteController for Kitkat, MediaController).

Disclaimer: I only quickly glanced at the source code for RadioDroid.
RadioDroid does not seem to do any of that (at least, not on my Nougat devices - maybe they do send a broadcast on JellyBean?). While it does seem to show the artist name and title in the notification, I suspect it's just a formatted string that the webradio sends along with the audio stream.

The point is, RadioDroid does not seem to handle the metadata in any way and also does not share it with other apps.

@nicolas-raoul I also opened #223 in which I would love to hear what you have to say. :+1:

**Comment by geecko86** [comment]
This also applies to TuneIn and other webradio apps.

**Comment by geecko86** [comment]
Also - I will soon implement ways to not rely exclusively on the metadata, but on the audio waves instead, using [AcoustID](https://acoustid.biz).

But even then, we'll need a file - not a stream.
