### ISSUE TITLE
Romanize asian characters

### ISSUE THREAD

**Issue by geecko86** [QuickLyric/QuickLyric#223]
The goals is to have a button to convert

* Japanese (hiragana, katakana, kanjis)
* Chinese
* Korean

to the latin alphabet to allow non-native speakers to follow the song phonetically.

[See this tweet](https://twitter.com/QuickLyric/status/862816292188950529).
Japanese speakers will quickly see that this is absolutely wrong. Shame on me, I should've checked.

What happens is that Kanjis are presumed by [xuender/unidecode](https://github.com/xuender/unidecode/) to be Chinese characters that should be transliterated in Mandarin. Therefore, we need a conversion table (a dictionary) from Kanjis to Kana.

* We need it to be of sufficient quality and size for proper transliteration of Japanese music.
* We need it to be as light as possible, so that it doesn't impact the APK size too much. For instance, we don't need a dictionary that converts Kanji to hiargana, katakana *and* romaji. Just one of the three will be sufficient.

Besides size, I have to admit I'm unable say what differentiates [these dictionaries](https://github.com/atilika/kuromoji#supported-dictionaries).

The lightest I was able to find is [nicolas-raoul/kakasi-java](https://github.com/nicolas-raoul/kakasi-java), but I was not able to make it work on Android. Nicolas has also worked on [nicolas-raoul/jakaroma](https://github.com/nicolas-raoul/jakaroma), apparently it's much better (**how so?**) but also much heavier. I'm also not sure I understand what makes **jakaroma** better than the lib it's based on ([atilika/kuromoji](https://github.com/atilika/kuromoji)).

Finally, an interesting idea would be to rely on a separate APK. That said I'm not sure I would be interested in maintaining such an app given the fact that I do not understand Japanese. QuickLyric would query this "dictionary app" via an intent and would obtain a romanized version of the input string.

**Comment by nicolas-raoul** [comment]
Indeed, this tweet is quite funny :-) Not only the kanji transliteration is wrong, but also some of the kana, for instance たって is never pronounced tatsute.

Kanji transliteration is a [difficult](http://d.hatena.ne.jp/hiiragi-june/20070815) exercise even for native Japanese linguists. My colleagues, litterature majors from Kyoto University, often argue with each other about a character's pronunciation. Pronunciation depends heavily on the context, who is speaking, in what situation, etc.
Kakasi tries to guess without looking at the context. It will always transliterate a word the same way, whatever is before/after. To add to its misery, even when translating a single word like 日本 its transliterations are often not the most popular ones (日本 is always transliterated to Nippon even though Nihon is more commonly used).
Kuromoji is much better, looking at the whole sentence and usually getting the transliteration right.
But Kuromoji only transliterates to kana, that's why I created Jakaroma which adds the last step kana→romaji.
I can try to make a separate APK. As a consumer, would you mind telling me what Android intent would be the most appropriate and natural to use for you?

**Comment by geecko86** [comment]
Great! Thanks for these explanations. :+1: 

On the top of my head, the intent would probably look close to something like this:

```
Intent romajiIntent = new Intent();
romajiIntent.setComponent(new ComponentName(TARGET_PACKAGE_NAME, TARGET_CLASS_NAME); // Explicitly targets the dictionary app
romajiIntent.putExtra(INPUT_FIELD_NAME, input); // CharSequence or String Array
romajiIntent.putExtra(RECEIVER_FIELD_NAME, myPackageName); // String (i.e. com.geecko.QuickLyric)
getActivity().sendBroadcast(romajiIntent);
```

The intent would be explicitly targeting the dictionary APK.
The idea here is that I can pass several Strings at once (i.e. title, artist and text). Once the dictionary APK gets the broadcast, it does the processing and eventually broadcasts it back to the app who made the request, using the package name provided in the extra field.

Sounds good?

**Comment by geecko86** [comment]
Ideally this APK would only contain a broadcast receiver in its manifest. No need for an activity.

**Comment by geecko86** [comment]
@nicolas-raoul Could you please let me know if you're interested in doing this? 🙂 If so, when?

This feature is definitely requested a lot and we'd like to be able to ship it in 15 days or so.

**Comment by nicolas-raoul** [comment]
Sorry I won't be able to do it soon unfortunately as I am very busywith
other projects :-/

**Comment by geecko86** [comment]
@nicolas-raoul That's fine. Until then, the app will ship with kuromoji and unidecode, which makes it between 15 and 20MB. Let me know if you have an ETA.

Cheers

**Comment by geecko86** [comment]
Hey @nicolas-raoul! I built this app based on Kuromoji. Feel free to fork it if you ever find time in your busy schedule :)

https://github.com/QuickLyric/Romanizer
https://play.google.com/store/apps/details?id=com.quicklyric.romanizer

**Comment by geecko86** [comment]
(Also, I corrected my embarassing tweet: https://twitter.com/QuickLyric/status/878700216681156609)

**Comment by nicolas-raoul** [comment]
Thanks a lot! :-)
I will remember this add-on when I need romanization in other apps.
