### ISSUE TITLE
F-Droid version and download lyrics

### ISSUE THREAD

**Issue by trmendes** [QuickLyric/QuickLyric#224]
The FDroid version is not updated and it is crashing every time I try to download all the lyrics. It works in the begging than makes my phone slow and than crashs.

**Comment by conrad-heimbold** [comment]
According to 
https://f-droid.org/wiki/page/com.geecko.QuickLyric , 
F-Droid has got the latest version (2.1). Check the source tags on github here as comparison.  Either you are wrong; or there is a bug on the side of F-Droid. 

Do you have a logcat? How to collect a logcat: google it! 
Otherwise, we won't be able to help you very much...

**Comment by conrad-heimbold** [comment]
The Google Play version does not seem to be open-source (the google-play branch only has got stub files). I am confused...

**Comment by geecko86** [comment]
The Google Play version has minor differencs. like AdMob and Firebase, hence it can't be distributed on F-Droid.

Anyway, either be patient or get it from Gplay.

**Comment by geecko86** [comment]
Also, logs are a lot of help.

**Comment by ildar** [comment]
I got an impression we don't see latest changes in github (see
https://github.com/QuickLyric/QuickLyric/issues/215#issuecomment-306055118
).  As the Master says, we need patience to see the latest changes.

**Comment by geecko86** [comment]
You'll be happy to know changes have been pushed.

I don't do a whole lot of testing but it seems to work fine. If you have a bug report to do, please provide more information.

It will be up on F-Droid next week I think. There might be some issues that need to be resolved because there is now some native code inside the app.

**Comment by ildar** [comment]
I am happy, yes, indeed.
Yet it'll come to F-Droid only after you tag the new version.

**Comment by ildar** [comment]
Please please tag or Release
as F-Droid currently ignores new commits until a tag discovered

**Comment by geecko86** [comment]
Still some bugs I need to fix

**Comment by ildar** [comment]
Ahh! I see. Ok

**Comment by jakejoh** [comment]
Is the version on F-Droid still getting updates? Currently, it's v2.1 from April 2017.

**Comment by geecko86** [comment]
No it doesn't.
That said, this GitHub repo is still getting updated (though it's at a slower pace) and it's pretty easy to build an APK.

**Comment by MarcRdC** [comment]
@geecko86 It seems that QuickLyric is not an open-source project anymore… The wiki page <https://github.com/QuickLyric/QuickLyric/wiki/Can-I-fork-this-project,-change-the-name,-put-it-on-Google-Play-and-pretend-it's-mine%3F> is perfectly understandable: the licensing costs you and you were bored of all the unauthorized forks. But this GitHub repo has not been updated for months. Perhaps you should be coherent and transparent and specify that the code here is outdated and that you don’t have intention to update it “regularly” — to say the least. Or you could just delete the repo.
