### ISSUE TITLE
batchdownload always stops a few songs before finishing

### ISSUE THREAD

**Issue by laundmo** [QuickLyric/QuickLyric#245]
hey there.

i was trying to use quicklyric to download all lyrics of songs in my spotify playlists, 5384 lyrics, but the download always stops at 5362 lyrics.

when i force kill the app none of my lyrics show up, and without it just doesnt continue downloading. i left it alone hoping it would download for 6h but no result. still stuck at 5362.

is there anything i can do to still be able to save all my lyrics? 

can you maybe add a feature for manually stopping a download, so that it still recognises the lyrics?

also, when i tried to go into settings while the download was "broken" the app crashed.

this is a huge issue since it stops me from downloading my lyrics. 

please tell me how i can provide more info

samsung galaxy s4 mini, android 4.4.2

latest QuickLyric version from google playstore

**Comment by laundmo** [comment]
UPDATE

Tried downloading from saved songs in spotify. only 2000 lyrics.

the notification after finishing said "downloaded lyrics for 0 songs"

and what do you know? no lyrics were downloaded. no new files showed up in my file manager. not while downloading and not after.

i am REALLY disappointed!!

**Comment by laundmo** [comment]
UPDATE again


not even refreshing when playing a song through spotify works. really disappointed.

**Comment by laundmo** [comment]
UPDATE again

 
ughh. not even manually downloading  lyrics works. its stuck in endless loading symbol.

**Comment by laundmo** [comment]
UPDATE

signed up as beta tester in google play

in the beta version downloading songs works

the app still wont detect the current song from spotify

PS: notification permission is enabled

**Comment by geecko86** [comment]
Hi Laundmo,

This repository is for the OSS version of QuickLyric, which you aren't using.

There were some issues with the Batch Downloading yesterday, but they got resolved.
We aren't running a beta at the moment, so I suspect you're simply running the latest build.

In order to help with your issues, I'm going to need more information. Right now I don't know which version of Android you're running, for instance.

The good news is that users can simply use the "send feedback" button in the app to send us all the relevant info, so that we can try to figure out what happened.

Let's continue this discussion via email ok?

**Comment by thewama33** [comment]
Stoo send fucking useless emails i dont care at all  and  uninstalled ur
app 😤😤

**Comment by laundmo** [comment]
okay sure. didnt know this wasnt the right repo
