### ISSUE TITLE
Please tag the current version

### ISSUE THREAD

**Issue by amotzkau** [QuickLyric/QuickLyric#249]
The F-Droid repository uses git tags to detect new versions. The last commit that was tagged in this repository is 2.1, so that's the version offered at F-Droid. Could you please create a new tag for the current version?

Thanks!

**Comment by geecko86** [comment]
Hi there,

We have chosen not to distribute on F-Droid anymore. If you were to clone this repo and compile the app yourself, you would see it's actually regressed since version 2.1.

I recommend getting the app on either APKMirror or the Play Store.

Maintaining a Free Software project that handles non-free, copyrighted lyrics is a challenge. [See this page on the wiki.](https://github.com/QuickLyric/QuickLyric/wiki/Can-I-fork-this-project,-change-the-name,-put-it-on-Google-Play-and-pretend-it's-mine%3F) for additional details.

This repo is still being maintained (though at a slower pace) and QuickLyric is still GPLv3.
